# rustfmt configuration for dbfast
# https://rust-lang.github.io/rustfmt/

# Stable options only
edition = "2021"
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
max_width = 100