# Nextest configuration
# Generated on 2025-09-10
# https://nexte.st/book/configuration.html

[profile.default]
# Number of tests to run simultaneously
test-threads = "num-cpus"

# Test timeout
slow-timeout = { period = "60s", terminate-after = 2 }
leak-timeout = "100ms"

[profile.default.junit]
path = "target/nextest/default/junit.xml"
store-success-output = false
store-failure-output = true

[profile.ci]
# CI-specific configuration
test-threads = 4
retries = 2
fail-fast = false
success-output = "never"
failure-output = "immediate-final"

[profile.ci.junit]
path = "target/nextest/ci/junit.xml"
store-success-output = true  
store-failure-output = true

[profile.coverage]
# Configuration for coverage runs
test-threads = 1
retries = 0
fail-fast = true

[test-groups]
# Group integration tests
integration = { max-threads = 1 }
# Serial test group for tests that must run sequentially
serial = { max-threads = 1 }

[[profile.default.overrides]]
filter = 'test(integration_)'
test-group = 'integration'

[[profile.default.overrides]]
filter = 'test(benchmark_)'
test-group = 'serial'