CREATE TABLE blog.tb_post (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pk_post UUID DEFAULT gen_random_uuid() NOT NULL,
    pk_author_user UUID NOT NULL,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    excerpt TEXT,
    featured_image_url VARCHAR(500),
    is_published BOOLEAN DEFAULT false,
    is_featured BOOLEAN DEFAULT false,
    published_at TIMESTAMPTZ,
    view_count INTEGER DEFAULT 0,

    -- Audit fields
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by UUID,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by UUID,
    deleted_at TIMESTAMPTZ,
    deleted_by UUID,

    CONSTRAINT tb_post_slug_key UNIQUE (slug),
    CONSTRAINT tb_post_pk_post_key UNIQUE (pk_post),
    CONSTRAINT fk_post_author_user FOREIGN KEY (pk_author_user)
        REFERENCES blog.tb_user(pk_user) ON DELETE CASCADE
);

-- Indexes for performance
CREATE INDEX idx_tb_post_author ON blog.tb_post(pk_author_user);
CREATE INDEX idx_tb_post_published ON blog.tb_post(is_published, published_at);
CREATE INDEX idx_tb_post_featured ON blog.tb_post(is_featured);
CREATE INDEX idx_tb_post_created_at ON blog.tb_post(created_at);

-- Documentation
COMMENT ON TABLE blog.tb_post IS '[Table: 010211 | Write-Side.Blog.Post] Stores blog posts with content and metadata.';
COMMENT ON COLUMN blog.tb_post.id IS 'Internal numeric primary key. Not used in joins.';
COMMENT ON COLUMN blog.tb_post.pk_post IS 'Public UUID used for joins and external references.';
COMMENT ON COLUMN blog.tb_post.pk_author_user IS 'UUID reference to the author user.';
COMMENT ON COLUMN blog.tb_post.title IS 'Post title for display and SEO.';
COMMENT ON COLUMN blog.tb_post.slug IS 'URL-friendly slug for the post, must be unique.';
COMMENT ON COLUMN blog.tb_post.content IS 'Full post content in Markdown or HTML.';
COMMENT ON COLUMN blog.tb_post.excerpt IS 'Short excerpt for post previews.';
COMMENT ON COLUMN blog.tb_post.featured_image_url IS 'URL to featured image for the post.';
COMMENT ON COLUMN blog.tb_post.is_published IS 'Whether the post is published and visible.';
COMMENT ON COLUMN blog.tb_post.is_featured IS 'Whether the post should be featured on homepage.';
COMMENT ON COLUMN blog.tb_post.published_at IS 'When the post was published.';
COMMENT ON COLUMN blog.tb_post.view_count IS 'Number of times the post has been viewed.';
